자바스크립트 문법 문제 풀이(~23.11.26)
dlfeksgo/algorithm-js pull request #1
Opened 2023-11-27 06:11 UTC by dlfeksgo

@f-lab-jake 멘토님, 이전까지 작성했던 문제 풀이 PR 드립니다.

- 백준과 프로그래머스 폴더로 분리했습니다.
- 각 파일 상단에 문제 링크를 주석으로 달았습니다.

2023-11-27 07:01 UTC, dlfeksgo commented
eslint 검사로 발견된 항목들을 수정 후 커밋했습니다. 

1. ' ' -> ” ”
2. 변수 선언 키워드 정정
3. 생략된 변수 선언 키워드 추가
4. parseInt radix parameter 추가
5. 삼항연산자 구문의 return 추가

*기타: 프로그래머스 문제 함수 호출부 생략 에러

2023-11-27 07:46 UTC, f-lab-jake requested changes
몇가지 바로 보이는 부분에 대해 리뷰했습니다. 예시로 하나씩 든것이고, 해당 가이드를 따라서 다른 코드도 리팩토링해봅시다. 그리고 왜 그 방법이 좋은지도 생각해봅시다. 별로 좋지 않다고 생각하면 반대의견을 준비하는것도 좋습니다.

2023-11-27 07:46 UTC, f-lab-jake commented on 00.baekjoon/008-2480.js
>  if (a === b && b === c) {
`console.log`를 한번만 쓰도록 고쳐봅시다

2023-11-27 07:46 UTC, f-lab-jake commented on 00.baekjoon/004-2588.js
>  console.log(Number(a) * Number(x_1));
`Number`의 자명한 중복을 제거합시다

2023-11-27 07:46 UTC, f-lab-jake commented on 00.baekjoon/011-15552.js
> +let result = "";
number의 배열로 바꿉시다

2023-11-27 07:46 UTC, f-lab-jake commented on 01.programmers-Lv0/004.js
> +  for (let i = 0; i < str.length; i++) {
`arr.push`를 한번으로 줄입시다

2023-11-27 07:46 UTC, f-lab-jake commented on 01.programmers-Lv0/019.js
> +  if (ineq === ">" && eq === "=") {
return 구문을 한번으로 줄입시다

2023-11-27 07:46 UTC, f-lab-jake commented on 01.programmers-Lv0/023.js
> +    return (sum = (a + b + c) * (a * a + b * b + c * c));
`sum =`을 왜 했나요?

2023-11-27 09:46 UTC, dlfeksgo commented on 01.programmers-Lv0/023.js
> +    return (sum = (a + b + c) * (a * a + b * b + c * c));
습관처럼 변수에 값을 담으려 했던 것 같아요. 제거 후 바로 값을 반환하도록 수정했습니다.

2023-11-27 10:00 UTC, dlfeksgo commented on 00.baekjoon/008-2480.js
>  if (a === b && b === c) {
console.log가 반복되는 다른 문제도 함께 리팩토링 하였습니다. [005-9498.js]

2023-11-27 10:00 UTC, dlfeksgo commented on 00.baekjoon/011-15552.js
> +let result = "";
배열로 변환하면서 split 코드 중복도 제거되었습니다.

2023-11-27 10:01 UTC, dlfeksgo commented on 01.programmers-Lv0/019.js
> +  if (ineq === ">" && eq === "=") {
삼항연산자 구문의 중복을 제거하고, 마지막 반환값에만 적용하였습니다.
비슷하게 [014.js] 문제도 if문을 삼항연산자로 개선하였습니다.

2023-12-01 01:27 UTC, dlfeksgo commented
@f-lab-jake 멘토님, 
기존 eslint-config에 에러가 생겨서 삭제 후 새로 세팅을 해보고 해당 파일로 올려보았습니다.
그리고 정리되지 않았던 반복문 코드를 전체적으로 개선 해보았습니다.

2023-12-02 02:53 UTC, f-lab-jake commented
eslint 안될때 메시지가 뭐였나요?

2023-12-02 13:58 UTC, dlfeksgo commented
바로 해결이 되어서 에러 메시지를 따로 메모해두지 못했어요. 
에러는 eslint 업데이트 후에 발생했고, eslint-config-gwyng과 extends 관련이었는데 다시 해보니 에러가 나지 않습니다 😥

2023-12-10 11:38 UTC, dlfeksgo commented
@f-lab-jake 
멘토님, 기존 풀이를 모두 타입스크립트로 변경했습니다. 
변경하면서 ESLint와 Prettier 셋팅을 수정했고, 멘토링 피드백 참고하여 다시 한 번 풀어보면서 개선 가능한 코드는 리팩토링 하였습니다.

2023-12-10 15:14 UTC, f-lab-jake requested changes

2023-12-10 15:14 UTC, f-lab-jake commented on 00.baekjoon/016-1181.ts
> +        else return 0;
불필요한 구문을 지워봅시다

2023-12-10 15:14 UTC, f-lab-jake commented on 00.baekjoon/017-18870.ts
> +}
처음부터 초기값을 넣어서 `Map`을 만들 방법이 있습니다

2023-12-10 15:14 UTC, f-lab-jake commented on 00.baekjoon/018-10814.ts
> +const people: (string | number)[][] = lines.map((v) => {
`[number, string][]` 타입이 낫습니다. 이런걸 튜플 타입이라고 합니다.

2023-12-10 15:14 UTC, f-lab-jake commented on 00.baekjoon/019-1472.ts
> +for (const v of str) {
`str.split('')`하면 문자열을 배열로 쪼갤수 있습니다

2023-12-10 15:14 UTC, f-lab-jake commented on 00.baekjoon/020-11047.ts
> +    .reverse();
체이닝 하지말고 `coins.reverse()`로 하는게 낫습니다. 왜일까요?

2023-12-10 15:14 UTC, f-lab-jake commented on 00.baekjoon/022-1541.ts
> +    if (i === 0) {
처음 한번의 순회에서만 이 조건에 걸리겠죠? 이런 패턴을 피해봅시다.

2023-12-10 15:14 UTC, f-lab-jake commented on 00.baekjoon/023-2839.ts
> +        break;
break는 값을 넘겨줄수 없습니다. return은 가능합니다. 함수로 감싸고 return을 써봅시다.

2023-12-10 15:14 UTC, f-lab-jake commented on 00.baekjoon/024-16953.ts
> +        flag = true;
마찬가지 입니다. 함수를 만들고 return을 씁시다.

2023-12-10 15:14 UTC, f-lab-jake commented on 01.programmers-Lv0/004.ts
> +        }
반복되는 구문을 줄여봅시다. 줄인다음 짧다는거 외에 어떤 점에서 가독성에 이점이 있는지 설명해봅시다.

2023-12-10 15:14 UTC, f-lab-jake commented on 01.programmers-Lv0/010.ts
> +    let str = [];
let 사용은 최댇한 피하는게 좋습니다. 왜일까요?

2023-12-10 15:14 UTC, f-lab-jake commented on 01.programmers-Lv0/025.ts
> +    num_list.map((num) => (num % 2 === 0 ? (even += num) : (odd += num)));
map의 오용입니다.

2023-12-10 15:14 UTC, f-lab-jake commented on 01.programmers-Lv0/027.ts
> +        }
숨겨진 중복이 있습니다.

2023-12-10 15:14 UTC, f-lab-jake commented on 01.programmers-Lv0/028.ts
> +        }
숨겨진 중복이 있습니다

2023-12-10 15:14 UTC, f-lab-jake commented on 01.programmers-Lv0/029.ts
> +        const data = arr[query[0]];
`query[0]` 같은건 이해하기가 정말 어렵습니다.
destructuring해서 이름을 붙여주는게 낫습니다.

2023-12-10 15:14 UTC, f-lab-jake commented on 01.programmers-Lv0/030.ts
> +    }
좀더 함수형으로 짜봅시다.

2023-12-10 15:14 UTC, f-lab-jake commented on 01.programmers-Lv0/031.ts
> +            i % query[2] === 0 ? (arr[i] += 1) : '';
값을 안쓸거면 삼항연산자를 피합시다.

2023-12-10 15:14 UTC, f-lab-jake commented on 01.programmers-Lv0/035.ts
> +    }
조건문의 순서를 바꿔서 중복을 줄일수있습니다

2023-12-11 12:18 UTC, bglgwyng requested changes

2023-12-11 15:02 UTC, f-lab-jake requested changes

2023-12-11 15:02 UTC, f-lab-jake commented on 01.programmers-Lv0/030.ts
>      return result;
잘했습니다. 그런데 함수형으로 고칠수있는 부분이 또있습니다.

2023-12-11 15:02 UTC, f-lab-jake commented on 01.programmers-Lv0/035.ts
> +        if (stk[stk.length - 1] >= arr[i]) stk.pop();
`stk.length`가 0 이상인 조건을 넣어주는게 낫습니다.
지금 `stk[-1]`이 `undefined`인 동작에 의존하고있어요. 그리고 `stk.at(-1)`이 가능합니다.

2023-12-11 15:12 UTC, dlfeksgo commented on 00.baekjoon/005-9498.ts
> +let grade: string = '';
린트 에러가 갑자기 해결되어 불필요한 초기화는 제거했습니다.

2023-12-11 15:14 UTC, dlfeksgo commented on 00.baekjoon/006-2884.ts
>  }
넵 다시 확인해보겠습니다!

2023-12-11 15:23 UTC, f-lab-jake requested changes

2023-12-11 16:55 UTC, dlfeksgo commented on 01.programmers-Lv0/032.ts
> +            answer.push(i);
변수를 사용해보지 않으려다 이상한 코드가 되버렸습니다...
boolean 값을 쓰지 않고 length 값을 활용하는 방법으로 개선해보았어요.

2023-12-11 23:46 UTC, f-lab-jake commented on 01.programmers-Lv0/032.ts
> +            answer.push(i);
힌트를 주자면 `answer`와 관련있습니다.

2023-12-11 23:51 UTC, f-lab-jake requested changes

2023-12-11 23:51 UTC, f-lab-jake commented on 01.programmers-Lv0/032.ts
> +        delCount === 0 && answer.push(i);
expresssion과 statement의 차이를 공부해옵시다.
그리고 일단 이건 if문을 쓰는게 낫습니다

2023-12-11 23:51 UTC, f-lab-jake commented on 00.baekjoon/006-2884.ts
> +time %= 1440;
요런건 60 * 12라 써주는게 낫습니다.
코드를 읽다가 뜬금없어 보이는 숫자를 magic number라고 하는데요, 린트룰중에 magic number를 허용하지 않는 경우도 있습니다.

2023-12-12 02:21 UTC, dlfeksgo commented on 01.programmers-Lv0/032.ts
> +        delCount === 0 && answer.push(i);
넵!

2023-12-12 02:21 UTC, dlfeksgo commented on 00.baekjoon/006-2884.ts
> +time %= 1440;
아하 넵! 더 명확하게 풀어쓰도록 하겠습니다

2023-12-12 08:10 UTC, f-lab-jake approved these changes

2023-12-13 01:59 UTC, merged